pipeline:
  name: jira-cve-checks
  identifier: jiracvechecks
  projectIdentifier: scorecard
  orgIdentifier: demo
  tags: {}
  stages:
    - stage:
        name: scan_jira_cve
        identifier: scan_jira_cve
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitCloneScripts
                  identifier: GitCloneScripts
                  spec:
                    connectorRef: account.svc_harness_git1
                    repoName: harness-infra
                    build:
                      type: branch
                      spec:
                        branch: <+pipeline.variables.idp_script_branch>
              - step:
                  type: Run
                  name: ExecuteScript
                  identifier: ExecuteScript
                  spec:
                    connectorRef: account.dockerhub
                    image: python:3.14.0a2-alpine3.20
                    shell: Sh
                    command: |-
                      echo "Executing cve scans for service <+matrix.repo_name>"
                      pip install  requests pyyaml docker

                      python3 /harness/harness-infra/idp/jira-cve-check.py\
                        --jira_url=<+pipeline.variables.jira_url>\
                        --jira_user=<+pipeline.variables.jira_email_account>\
                        --jira_api_key=<+pipeline.variables.jira_token>\
                        --harness_account_id=<+account.identifier>\
                        --harness_api_token=<+pipeline.variables.HARNESS_TOKEN>\
                        --base_path="/harness"\
                        --servicename=<+matrix.repo_name>
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.cigeneral
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        strategy:
          matrix:
            repo_name:
              - demo-service
              - test-service
              - abc-service
            parallelism: 2
  variables:
    - name: jira_email_account
      type: String
      description: ""
      required: false
      value: svc.engprod@acme.com
    - name: HARNESS_TOKEN
      type: Secret
      description: ""
      required: false
      value: org.harness_idp_token
    - name: jira_url
      type: String
      description: ""
      required: false
      value: https://acme.atlassian.net
    - name: idp_script_branch
      type: String
      description: ""
      required: false
      value: main
    - name: jira_token
      type: Secret
      description: ""
      required: false
      value: account.jira_automation
